<a href="https://colab.research.google.com/github/24f3003058/DL-GenAI/blob/main/DeepLearning1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
data = pd.Series([1,2,3])
data

0    1
1    2
2    3
dtype: int64

In [4]:
data[1]

np.int64(2)

In [5]:
var={
    "cal":[100,200,300],
    "dura":[12,14,16]
}
df=pd.DataFrame(var)
df

   cal  dura
0  100    12
1  200    14
2  300    16

In [6]:
print(df.loc[2])

cal     300
dura     16
Name: 2, dtype: int64

In [7]:
print(type(df.loc[2]))

<class 'pandas.core.series.Series'>